# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - RichySoaCa2

on:
  push:
    branches:
      - client
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build API project
        run: dotnet build ./Campus-events-api/Campus-events-api.csproj --configuration Release

      - name: Publish API project
        run: dotnet publish ./Campus-events-api/Campus-events-api.csproj -c Release -o ${{ env.DOTNET_ROOT }}/publish

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ env.DOTNET_ROOT }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6ED70B8302954DFAB56F09A2AB3D70AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1EED22A60194EC2AFE538C43EA3E0BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB8A924DA2F1489A9B351CD33E9374C9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: RichySoaCa2
          slot-name: Production
          package: publish


