name: Build and deploy ASP.Net Core app to Azure Web App - RichySoaCa2

on:
  push:
    branches:
      - client
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Show csproj path (debug)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | Select-Object FullName

      - name: Restore
        run: dotnet restore "campus-events-api/Campus-events-api/Campus-events-api.csproj"

      - name: Build
        run: dotnet build "campus-events-api/Campus-events-api/Campus-events-api.csproj" -c Release --no-restore

      - name: Publish
        run: dotnet publish "campus-events-api/Campus-events-api/Campus-events-api.csproj" -c Release -o "${{ env.DOTNET_ROOT }}/publish" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ env.DOTNET_ROOT }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6ED70B8302954DFAB56F09A2AB3D70AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1EED22A60194EC2AFE538C43EA3E0BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB8A924DA2F1489A9B351CD33E9374C9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RichySoaCa2'
          slot-name: 'Production'
          package: publish

